"""Remove reminders from user_settings

Revision ID: 2a74fb88ed16
Revises: 8869dbbd6299
Create Date: 2025-04-05 00:40:28.166123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a74fb88ed16'
down_revision: Union[str, None] = '8869dbbd6299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('today_schedule_digest', sa.Boolean(), nullable=True))
    op.drop_column('user_settings', 'reminders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('reminders', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'today_schedule_digest')
    # ### end Alembic commands ###
