"""Replace group_name with group_id in schedule_cache

Revision ID: 377beb82abdf
Revises: 5416787be791
Create Date: 2025-04-16 23:19:18.072145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377beb82abdf'
down_revision: Union[str, None] = '5416787be791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_cache', sa.Column('week_start', sa.Date(), nullable=False))
    op.drop_index('ix_schedule_cache_date', table_name='schedule_cache')
    op.create_index(op.f('ix_schedule_cache_week_start'), 'schedule_cache', ['week_start'], unique=False)
    op.drop_column('schedule_cache', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_cache', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schedule_cache_week_start'), table_name='schedule_cache')
    op.create_index('ix_schedule_cache_date', 'schedule_cache', ['date'], unique=False)
    op.drop_column('schedule_cache', 'week_start')
    # ### end Alembic commands ###
