"""add inet_id to users

Revision ID: 86ee98394efc
Revises: 3513b3682e90
Create Date: 2025-04-04 22:04:19.022075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ee98394efc'
down_revision: Union[str, None] = '3513b3682e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_inet_id'), 'users', ['inet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_inet_id'), table_name='users')
    op.drop_column('users', 'inet_id')
    # ### end Alembic commands ###
