"""delete index from inet_id

Revision ID: e9d11651553a
Revises: 86ee98394efc
Create Date: 2025-04-04 22:09:47.456253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d11651553a'
down_revision: Union[str, None] = '86ee98394efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_inet_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_inet_id', 'users', ['inet_id'], unique=False)
    # ### end Alembic commands ###
